Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [2]:
import numpy as np

In [3]:
list1 = [1,2,3,4,5]

In [4]:
array_list = np.array([1,2,3,4,5])

In [8]:
print(type(list1))

<class 'list'>


In [9]:
print(type(array_list))

<class 'numpy.ndarray'>


Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [12]:
list2 = [1,2,3,4,5]

array_list1= ([1,2,3,4,5])

In [14]:
for i in list2:
    print(type(i))

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>


In [15]:
for element in array_list1:
    print(type(array_list1))

<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>


Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)

In [22]:
list3 =[1,2,3,4,5]

array_list2 = np.array(object=list3 ,dtype=int)

print(array_list2)

for j in array_list2:
    print(type(j))

[1 2 3 4 5]
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [23]:
ar = np.array([[1,2,3],[2,3,4]])

In [28]:
shape_num = ar.shape

In [29]:
shape_num

(2, 3)

In [30]:
size_num = ar.size

In [31]:
size_num

6

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
#[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [33]:
zeros_matrix = np.zeros((3,3))
print(zeros_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [34]:
matrix_shape = np.eye(5)
print(matrix_shape)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
